services:
  aidas-web:
    image: ${IMAGE_NAME}
    ports:
      - "8000:8000"
    environment:
      DB_URL: postgresql://aidas_user:aidas_password@172.16.8.202:5432/aidas_db
    volumes:
      - aidas_logs:/var/log/aidas

  promtail:
    image: grafana/promtail:3.0.0
    volumes:
      - aidas_logs:/var/log/aidas:ro
      - ./promtail-config.yaml:/etc/promtail/config.yaml
    command: -config.file=/etc/promtail/config.yaml

volumes:
  aidas_logs: