# aidas/deploy/onprem/ansible/roles/promtail_agent/defaults/main.yml
# 역할:
# - Promtail agent 기본 변수 정의
# - 호출 시점: promtail_agent role 실행 시 자동 로드
# - 수행 흐름:
#   - Loki endpoint, Promtail config 경로, 수집 대상 로그 파일 경로 지정

---
promtail_base_dir: /opt/promtail
promtail_config_dir: /opt/promtail/config

promtail_image: grafana/promtail:3.0.0
promtail_positions_dir: /var/lib/promtail
promtail_positions_file: /var/lib/promtail/positions.yaml

promtail_loki_url: "http://172.16.8.201:3100/loki/api/v1/push"
promtail_log_path: /var/log/*.log
promtail_job_name: system-logs